services:
  # llama:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.llama
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./model:/app/model
  #   environment:
  #     - MODEL_PATH=/app/model/llama

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017" # hide the port after dev phase is over
    volumes:
      - mongodb_data:/data/db

  pgvector:
    image: ankane/pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
  mongodb_data:
